version: '3'

services:
  web_app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - config/docker.env
    depends_on:
      - database
      - redis
      - jobs
    stdin_open: true
    tty: true
    networks:
      - network

  database:
    image: postgres:12.3
    env_file:
      - config/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - network

  redis:
    image: 'redis:7.0.5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    env_file:
      - config/docker.env
    volumes:
      - 'redis_client:/var/lib/redis/data'
    networks:
      - network

  jobs:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq -q default
    env_file:
      - config/docker.env
    volumes:
      - '.:/usr/src/app'
    networks:
      - network

volumes:
  db_data:
  redis_client:

networks:
  network:
    driver: bridge
