default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: blz_development


test:
  <<: *default
  database: blz_test

production:
  <<: *default
  database: blz_production
  username: blz
