default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blz_development
  username: postgres
  password:

test:
  <<: *default
  database: blz_test
  username: postgres
  password:

production:
  <<: *default
  database: blz_production
  username: blz
  password: <%= ENV['BLZ_DATABASE_PASSWORD'] %>
