default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") || Rails.application.credentials[Rails.env.to_sym][:database][:username] %>
  password: <%= ENV.fetch("DB_PASSWORD") || Rails.application.credentials[Rails.env.to_sym][:database][:password] %>
  host: <%= ENV.fetch("DB_HOST") || Rails.application.credentials[Rails.env.to_sym][:database][:host] %>

development:
  <<: *default
  database: blz_development

test:
  <<: *default
  database: blz_test

production:
  <<: *default
  database: blz_production
