default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] || ENV.fetch("DB_USERNAME") %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] || ENV.fetch("DB_PASSWORD") %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] || ENV.fetch("DB_HOST") %>

development:
  <<: *default
  database: blz_development

test:
  <<: *default
  database: blz_test

production:
  <<: *default
  database: blz_production
